[package]
name = "vigenere"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
panic = "abort"

[dependencies]

[dev-dependencies]
"quickcheck" = "1.0"
"regex" = "1.7"
